### ISSUE TITLE
L2 index returns 'squared Euclidean distance' instead of 'Euclidean distance'

### ISSUE THREAD

**Issue by ashfaq92** [stepstone-tech/hnswlib-jna#5]
**Code:**

        float[] p1 = {30.0f, 90.0f};
        Index index = new Index(SpaceName.L2, 2);
        index.initialize(2);
        index.addItem(p1);
        float[] query_point = {109.0f, 70.0f};
        QueryTuple result = index.knnQuery(query_point, 1);

        System.out.println("Query Results: ");
        System.out.println(Arrays.toString(result.getCoefficients()));
        System.out.println(Arrays.toString(result.getLabels()));

**Expected Output:**

![image](https://user-images.githubusercontent.com/28701122/86135208-13de4180-bb1d-11ea-9e28-a312213f357b.png)

**Output:**

Query Results: 
[6641.0]
[0]

We can see square_root of 6641.0 is exactly the expected output. So, the method is not taking the square root. In other words, it is returning squared euclidean distance.

**Comment by hussamaa** [comment]
Hi @ashfaq92,

Thanks for your feedback. We'll have a look into it.

BR,
Hussama

**Comment by hussamaa** [comment]
@ashfaq92,

In our applications we used mostly IP, Consine, so I was afraid we missed something on the bindings to the original Hnswlib. I double checked and we are in line with the original library. 

```
import hnswlib

p = hnswlib.Index(space = 'l2', dim = 2)

p.init_index(max_elements = 2, ef_construction = 200, M = 16)
p.add_items([30, 90], 1)
p.knn_query([109, 70], k = 1)

(array([[1]], dtype=uint64), array([[6641.]], dtype=float32))
```

Could you please double check with them if that could be an issue? https://github.com/nmslib/hnswlib

Thanks a lot,
Hussama

**Comment by ashfaq92** [comment]
I think it is okay. Squared euclidean distance is often taken as equivalent to Euclidean distance. User can manually take the square root. After all, both represent `L2` norm

**Comment by ashfaq92** [comment]
I think it is okay. Squared euclidean distance is often taken as equivalent to Euclidean distance. User can manually take the square root. After all, both represent `L2` norm
